# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JiraTimeAssist.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(540, 233)
        main_window.setMinimumSize(QtCore.QSize(540, 233))
        main_window.setMaximumSize(QtCore.QSize(540, 233))
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frm_top = QtWidgets.QFrame(self.centralwidget)
        self.frm_top.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frm_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_top.setObjectName("frm_top")
        self.lbl_filter = QtWidgets.QLabel(self.frm_top)
        self.lbl_filter.setGeometry(QtCore.QRect(20, 10, 47, 21))
        self.lbl_filter.setObjectName("lbl_filter")
        self.cb_filter = QtWidgets.QComboBox(self.frm_top)
        self.cb_filter.setGeometry(QtCore.QRect(90, 10, 69, 22))
        self.cb_filter.setObjectName("cb_filter")
        self.btn_add_task = QtWidgets.QPushButton(self.frm_top)
        self.btn_add_task.setGeometry(QtCore.QRect(440, 10, 75, 23))
        self.btn_add_task.setObjectName("btn_add_task")
        self.cb_ticket = QtWidgets.QComboBox(self.frm_top)
        self.cb_ticket.setGeometry(QtCore.QRect(360, 10, 69, 22))
        self.cb_ticket.setObjectName("cb_ticket")
        self.verticalLayout.addWidget(self.frm_top)
        self.frm_center = QtWidgets.QFrame(self.centralwidget)
        self.frm_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_center.setObjectName("frm_center")
        self.grp_ticket = QtWidgets.QGroupBox(self.frm_center)
        self.grp_ticket.setGeometry(QtCore.QRect(10, 20, 502, 80))
        self.grp_ticket.setMinimumSize(QtCore.QSize(502, 80))
        self.grp_ticket.setObjectName("grp_ticket")
        self.lcd_ticket_time = QtWidgets.QLCDNumber(self.grp_ticket)
        self.lcd_ticket_time.setGeometry(QtCore.QRect(170, 40, 64, 23))
        self.lcd_ticket_time.setObjectName("lcd_ticket_time")
        self.btn_start = QtWidgets.QPushButton(self.grp_ticket)
        self.btn_start.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.grp_ticket)
        self.btn_stop.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_submit = QtWidgets.QPushButton(self.grp_ticket)
        self.btn_submit.setGeometry(QtCore.QRect(340, 40, 75, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.btn_delete = QtWidgets.QPushButton(self.grp_ticket)
        self.btn_delete.setGeometry(QtCore.QRect(420, 40, 75, 23))
        self.btn_delete.setObjectName("btn_delete")
        self.lbl_description = QtWidgets.QLabel(self.grp_ticket)
        self.lbl_description.setGeometry(QtCore.QRect(10, 20, 481, 16))
        self.lbl_description.setObjectName("lbl_description")
        self.verticalLayout.addWidget(self.frm_center)
        self.frm_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frm_bottom.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frm_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_bottom.setObjectName("frm_bottom")
        self.lbl_total = QtWidgets.QLabel(self.frm_bottom)
        self.lbl_total.setGeometry(QtCore.QRect(10, 10, 47, 21))
        self.lbl_total.setObjectName("lbl_total")
        self.lcd_total_time = QtWidgets.QLCDNumber(self.frm_bottom)
        self.lcd_total_time.setGeometry(QtCore.QRect(70, 10, 64, 23))
        self.lcd_total_time.setObjectName("lcd_total_time")
        self.btn_settings = QtWidgets.QPushButton(self.frm_bottom)
        self.btn_settings.setGeometry(QtCore.QRect(440, 10, 75, 23))
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout.addWidget(self.frm_bottom)
        main_window.setCentralWidget(self.centralwidget)

        self.translate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Jira Time Assist"))
        self.lbl_filter.setText(_translate("MainWindow", "Filter:"))
        self.btn_add_task.setText(_translate("MainWindow", "Add Task"))
        self.grp_ticket.setTitle(_translate("MainWindow", "TicketName"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))
        self.lbl_description.setText(_translate("MainWindow", "Ticket Description"))
        self.lbl_total.setText(_translate("MainWindow", "Total:"))
        self.btn_settings.setText(_translate("MainWindow", "Settings"))