from PyQt5 import QtCore, QtGui, QtWidgets


class UiSettings(object):
    def setup_ui(self, settings):
        settings.setObjectName("Settings")
        settings.resize(279, 139)
        settings.setMinimumSize(QtCore.QSize(279, 139))
        settings.setMaximumSize(QtCore.QSize(279, 139))
        self.centralwidget = QtWidgets.QWidget(settings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.edt_username = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_username.setObjectName("edt_username")
        self.gridLayout.addWidget(self.edt_username, 1, 1, 1, 1)
        self.edt = QtWidgets.QLineEdit(self.centralwidget)
        self.edt.setObjectName("edt")
        self.gridLayout.addWidget(self.edt, 2, 1, 1, 1)
        self.edt_host = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_host.setObjectName("edt_host")
        self.gridLayout.addWidget(self.edt_host, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(self.centralwidget)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout.addWidget(self.lbl_password, 2, 0, 1, 1)
        self.lbl_host = QtWidgets.QLabel(self.centralwidget)
        self.lbl_host.setObjectName("lbl_host")
        self.gridLayout.addWidget(self.lbl_host, 0, 0, 1, 1)
        self.lbl_username = QtWidgets.QLabel(self.centralwidget)
        self.lbl_username.setObjectName("lbl_username")
        self.gridLayout.addWidget(self.lbl_username, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(self.frame)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_close = QtWidgets.QPushButton(self.frame)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 1)
        settings.setCentralWidget(self.centralwidget)

        self.translate_ui(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def translate_ui(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("Settings", "Settings"))
        self.lbl_password.setText(_translate("Settings", "Password:"))
        self.lbl_host.setText(_translate("Settings", "Host:"))
        self.lbl_username.setText(_translate("Settings", "Username:"))
        self.btn_save.setText(_translate("Settings", "Save"))
        self.btn_close.setText(_translate("Settings", "Close"))